spring:
  application:
    name: naughty-harmonics-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=nh
    username: service
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
clientId: '417615307974-tmf5c2h8u8tndege9riuq8882pl8kd7j.apps.googleusercontent.com'
